security:
  token:
    secret: ThWmYq3t6w9z$C&F)J@NcRfUjXn2r4u7x!A%D*G-KaPdSgVkYp3s6v8y/B?E(H+M

#spring:
#  datasource:
#    url: jdbc:h2:file:./data/database
#    username: sa
#    password: sa
#  jpa:
#    hibernate:
#      ddl-auto: update

server:
  port: 8080