spring:
  profiles:
    #use demo as the active profile to generate demo data (DemoEnvironmentGenerator.java)
    active: demo
  jpa:
    open-in-view: false
  servlet:
    # Enable Image upload
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
logging:
  file:
    name: "palletpals.log"
  pattern:
    level: INFO
security:
  token:
    secret: ThWmYq3t6w9z$C&F)J@NcRfUjXn2r4u7x!A%D*G-KaPdSgVkYp3s6v8y/B?E(H+M
server:
  port: 8080